# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PsEaTe-KFSaCenc9yC2jspKSfXx5BNZR
"""

import zipfile
import os
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

"""## 1. Extracting Data"""

zip_file_path = '/content/archive (1).zip'
extract_dir = '/content/extracted_data'

# Create the directory if it doesn't exist
os.makedirs(extract_dir, exist_ok=True)

with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extract_dir)

print(f"'{zip_file_path}' extracted to '{extract_dir}'")

# List contents of the extracted directory
print("Contents of extracted directory:")
for root, dirs, files in os.walk(extract_dir):
    for file in files:
        print(os.path.join(root, file))

"""## 2. Load and Initial Data Inspection"""

data_path = '/content/extracted_data/Klasifikasi Tingkat Kemiskinan di Indonesia.csv'
df = pd.read_csv(data_path, sep=';')

# Clean column names by stripping leading/trailing whitespace
df.columns = df.columns.str.strip()

# List of columns identified as numerical based on analysis of the dataset header
numerical_cols_to_clean = [
    'Persentase Penduduk Miskin (P0) Menurut Kabupaten/Kota (Persen)',
    'Rata-rata Lama Sekolah Penduduk 15+ (Tahun)',
    'Pengeluaran per Kapita Disesuaikan (Ribu Rupiah/Orang/Tahun)',
    'Indeks Pembangunan Manusia',
    'Umur Harapan Hidup (Tahun)',
    'Persentase rumah tangga yang memiliki akses terhadap sanitasi layak',
    'Persentase rumah tangga yang memiliki akses terhadap air minum layak',
    'Tingkat Pengangguran Terbuka',
    'Tingkat Partisipasi Angkatan Kerja',
    'PDRB atas Dasar Harga Konstan menurut Pengeluaran (Rupiah)'
]

for col in numerical_cols_to_clean:
    if col in df.columns:
        # Clean potential non-numeric characters (spaces, commas) and convert to numeric
        # Assuming space can act as a decimal separator in some cases based on initial df.head()
        df[col] = df[col].astype(str).str.replace('.', '', regex=False) # Remove thousands separator
        df[col] = df[col].astype(str).str.replace(',', '.', regex=False) # Replace comma decimal with dot decimal
        df[col] = pd.to_numeric(df[col], errors='coerce') # Convert to numeric, coerce errors to NaN


print("### First 5 rows of the dataset after fixing separator and cleaning numerical columns:")
print(df.head())

print("\n### Dataset Info after fixing separator and cleaning:")
df.info()

print("\n### Dataset Description after fixing separator and cleaning:")
print(df.describe(include='all'))

"""## 2. Preprocessing Data

### a. Handling Missing Values
"""

print("### Missing values before preprocessing (after initial cleaning):")
missing_before_fillna = df.isnull().sum()
print(missing_before_fillna[missing_before_fillna > 0]) # Only print columns with missing values

# Handle missing values: fill with median for numerical columns identified in the previous step
for col in numerical_cols_to_clean:
    if col in df.columns and df[col].isnull().any():
        df[col].fillna(df[col].median(), inplace=True)

print("\n### Missing values after imputation:")
print(df.isnull().sum()[df.isnull().sum() > 0]) # Only print columns with remaining missing values

"""### b. Encoding Categorical Features"""

# Drop rows where the target variable 'Klasifikasi Kemiskinan' is NaN
df_cleaned = df.dropna(subset=['Klasifikasi Kemiskinan']).copy()

# Separate features (X) and target (y)
# 'Klasifikasi Kemiskinan' is the target variable
# 'Provinsi' and 'Kab/Kota' are categorical. Drop 'Kab/Kota' to avoid high dimensionality for now.
X = df_cleaned.drop(['Klasifikasi Kemiskinan', 'Kab/Kota'], axis=1)
y = df_cleaned['Klasifikasi Kemiskinan'] # This is already numerical, so no mapping needed.

# One-Hot Encoding for 'Provinsi'
ohe = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
encoded_provinces = ohe.fit_transform(X[['Provinsi']])
encoded_df = pd.DataFrame(encoded_provinces, columns=ohe.get_feature_names_out(['Provinsi']))

# Drop original 'Provinsi' and concatenate encoded features
X = X.drop('Provinsi', axis=1)
X = pd.concat([X.reset_index(drop=True), encoded_df.reset_index(drop=True)], axis=1) # Reset index to avoid alignment issues

# The target 'Klasifikasi Kemiskinan' is already numerical (0, 1, etc.)
# Convert to int if it's float (e.g., 0.0, 1.0) for consistency with class labels
y_encoded = y.astype(int)

print("### First 5 rows of features (X) after encoding:")
print(X.head())
print("\n### First 5 rows of target (y) after encoding:")
print(y_encoded.head())

"""### c. Scaling Numerical Features"""

# Identify numerical columns for scaling among the remaining features in X
# These are the columns that were cleaned and not one-hot encoded or dropped.
# Use the 'numerical_cols_to_clean' list defined previously for accurate selection.
numerical_cols_for_scaling = [col for col in numerical_cols_to_clean if col in X.columns]

# Initialize StandardScaler
scaler = StandardScaler()

# Apply scaling to numerical columns
X[numerical_cols_for_scaling] = scaler.fit_transform(X[numerical_cols_for_scaling])

print("### First 5 rows of features (X) after scaling numerical columns:")
print(X.head())

"""## 3. Split Data"""

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded)

print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

# Check the distribution of the target variable in train and test sets
print("\nDistribution of target in training set:")
print(y_train.value_counts(normalize=True))
print("\nDistribution of target in test set:")
print(y_test.value_counts(normalize=True))

"""## 4. Modeling SVM"""

# Initialize the SVM classifier with an RBF kernel
# The RBF kernel is chosen because it can handle non-linear relationships in the data.
# 'C' is a regularization parameter, 'gamma' defines the influence of a single training example.
svm_model = SVC(kernel='rbf', random_state=42)

# Train the model on the training data
svm_model.fit(X_train, y_train)

print("SVM model with RBF kernel has been successfully trained.")

"""## 5. Evaluasi Model"""

# Make predictions on the test set
y_pred = svm_model.predict(X_test)

# Calculate evaluation metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted', zero_division=0)
recall = recall_score(y_test, y_pred, average='weighted', zero_division=0)
f1 = f1_score(y_test, y_pred, average='weighted', zero_division=0)

print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")

# Analyze for overfitting/underfitting
# It's good practice to also check training accuracy to compare with test accuracy
y_train_pred = svm_model.predict(X_train)
train_accuracy = accuracy_score(y_train, y_train_pred)

print(f"\nTraining Accuracy: {train_accuracy:.4f}")
print(f"Test Accuracy: {accuracy:.4f}")

if train_accuracy > accuracy + 0.1: # A common heuristic for significant difference
    print("\nAnalysis: The model might be overfitting as training accuracy is significantly higher than test accuracy.")
elif train_accuracy < accuracy - 0.05: # A smaller threshold for underfitting
    print("\nAnalysis: The model might be underfitting as training accuracy is lower than test accuracy, indicating it didn't learn well enough.")
else:
    print("\nAnalysis: The model seems to be performing consistently on both training and test sets, suggesting a good fit.")

"""## 6. Visualisasi

### a. Distribusi Kelas Target
"""

plt.figure(figsize=(7, 5))
sns.countplot(x=y_encoded, palette='viridis')
plt.title('Distribution of Target Classes (0: Rendah, 1: Sedang, 2: Tinggi)')
plt.xlabel('Klasifikasi Kemiskinan')
plt.ylabel('Count')
plt.show()

"""### b. Confusion Matrix"""

cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['Rendah', 'Sedang', 'Tinggi'], yticklabels=['Rendah', 'Sedang', 'Tinggi'])
plt.title('Confusion Matrix')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()